name: MicroGen CI

on:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/release-drafter.yml'
      - '.github/stale.yml'
      - '.dependabot/**'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/release-drafter.yml'
      - '.github/stale.yml'
      - '.dependabot/**'

jobs:
  build:
    name: "JDK 11 Build"
    runs-on: ubuntu-latest
    # Skip draft PRs and those with WIP in the subject, rerun as soon as its removed
    if: "github.event_name != 'pull_request' || ( \
           github.event.pull_request.draft == false && \
           github.event.pull_request.state != 'closed' && \
           contains(github.event.pull_request.title, 'wip ') == false && \
           contains(github.event.pull_request.title, '[wip]') == false && \
           (
             github.event.action != 'edited' || \
             contains(github.event.changes.title.from, 'wip ') || \
             contains(github.event.changes.title.from, '[wip]') \
           ) \
         )"
    steps:
    - uses: actions/checkout@v2
    - uses: n1hility/cancel-previous-runs@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven dependencies
      uses: actions/cache@v2
      env:
        cache-name: cache-maven-dependencies
      with:
        # maven dependencies are stored in `~/.m2/repository` on Linux/macOS
        path: ~/.m2/repository
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('microgen-bom/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Build with Maven
      run: ./mvnw -e -B install --file pom.xml -s settings.xml
